/*
  Warnings:

  - Changed the type of `major` on the `partners` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- CreateEnum
CREATE TYPE "PartnerMajor" AS ENUM ('EMPLOYER_GENERAL', 'TRAINING_EDUCATION', 'ASSISTIVE_DEVICES_PROVIDER', 'ASSISTIVE_TECH_SOFTWARE', 'HEALTHCARE_REHABILITATION', 'NGO_NONPROFIT', 'GOVERNMENT_AGENCY', 'IT_SOFTWARE', 'BPO_CALL_CENTER', 'MANUFACTURING', 'RETAIL_ECOMMERCE', 'LOGISTICS_TRANSPORT', 'HOSPITALITY_TOURISM', 'FINANCIAL_SERVICES', 'LEGAL_SERVICES', 'MEDIA_COMMUNICATIONS', 'HOUSING_SERVICES', 'ACCESSIBILITY_SERVICES', 'DATA_ANNOTATION_TRANSLATION', 'AGRICULTURE_CONSTRUCTION', 'COMMUNITY_VOLUNTEER', 'OTHER');

-- AlterTable
ALTER TABLE "partners" DROP COLUMN "major",
ADD COLUMN     "major" "PartnerMajor" NOT NULL;
