// eslint-disable-next-line import/order
import type { Metadata } from "next";

import "./globals.css";

 
import { ThemeProvider } from "next-themes";
// eslint-disable-next-line import/order
import { Toaster } from "sonner";
import QueryProvider from "@/context/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <Toaster
          position="top-center"
          richColors
          closeButton
          toastOptions={{
            className: "bg-white text-black dark:bg-gray-800 dark:text-white",
            style: {
              fontSize: "14px",
              padding: "10px 15px",
            },
          }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
